name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  appwrite: ^13.0.0
  flutter:
    sdk: flutter
  http: ^0.13.0
  googleapis: ^9.0.0
  googleapis_auth: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
