name: Trestle
description: A block-based word processor that auto-layouts your content.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  path_provider: ^2.1.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  intl: ^0.18.1
  google_fonts: ^3.0.1
  flutter_markdown: ^0.7.4+3
  appwrite: ^13.0.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/.env